### ISSUE TITLE
OSError: SavedModel file does not exist at

### ISSUE THREAD

**Issue by zhou-sumei** [padriba/NLP_MeTaxa#3]
Hi, pardriba,
Thanks for you nice work fof this software, It provides me a new way to assign the taxonomy. I installed it from source code followed the instruction in a new conda environment. And the relevant packages was also installed. But when I tried the example, there is an error:

> 2022-02-14 11:50:08.362263: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory;
 LD_LIBRARY_PATH: /home/zhousumei/usr/lib:/picb/evolgen/users/zhousumei/my_toolkits/libjpeg/:/home/zhousumei/usr/lib:/picb/evolgen/users/zhousumei/my_toolkits/libjpeg/jpeg-8d1:/home/zhousumei/usr/lib:/home/zhousumei/usr/lib:/home/
zhousumei/usr/lib:::::::/picb/evolgen/users/zhousumei/my_toolkits/libjpeg/lib
2022-02-14 11:50:08.362317: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "get_Taxa.py", line 49, in <module>
    model = tf.keras.models.load_model(file,custom_objects={'precision':precision,'recall':recall})
  File "/picb/evolgen/users/zhousumei/miniconda/envs/NLP_Metaxa/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 186, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/picb/evolgen/users/zhousumei/miniconda/envs/NLP_Metaxa/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: model_220.h5/{saved_model.pbtxt|saved_model.pb}

my command: 
`python3 get_Taxa.py 1`
and the current workspacer is :
![image](https://user-images.githubusercontent.com/74159766/153797360-35994b55-7276-427c-b814-5028a9c7529b.png)

Looking forward your reply!

**Comment by zhou-sumei** [comment]
This problem have been solved, I downloaded the mode_220.h5 file (384M) again then the programe run successfully. Maybe at the first time  this file was destroied during the download process.

**Comment by padriba** [comment]
Thank you for being interested in my work. Please let me know if you have any problems.
